[manifest]
version = "1.0.0"
priority = 2147483647

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
payload = '''
--- @diagnostic disable
local imm = require("imm")
imm.path = "{{lovely_hack:patch_dir}}"
if imm.initstatus.wrap then
	require("imm.init.early_error")
else
	local ok, err = imm.init()
	if not ok then print('imm: error: ', err) end
end
'''

