[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.module]
source = "imm/include/nativefs.lua"
before = "main.lua"
name = "imm.nativefs"

[[patches]]
[patches.module]
source = "imm/include/json.lua"
before = "main.lua"
name = "imm.json"

[[patches]]
[patches.module]
source = "imm/module.lua"
before = "main.lua"
name = "imm"

[[patches]]
[patches.module]
source = "imm/init/early_error_handler.lua"
before = "main.lua"
name = "imm.init.early_error_handler"

[[patches]]
[patches.module]
source = "imm/init/early_error.lua"
before = "main.lua"
name = "imm.init.early_error"

[[patches]]
[patches.module]
source = "imm/lib/util/str.lua"
before = "main.lua"
name = "imm.lib.util.str"
